### ISSUE TITLE
Tag bot

### ISSUE THREAD

**Issue by prmichaelsen** [giulionf/realtweetornotbot#74]
**Is your feature request related to a problem? Please describe.**
It would be cool to be able to tag the bot for processing on posts which it hasn’t scanned.

**Comment by giulionf** [comment]
Can you elaborate? Like mentioning the username for it to comment?

**Comment by prmichaelsen** [comment]
Yes, precisely.

**Comment by giulionf** [comment]
Closed by https://github.com/giulionf/realtweetornotbot/pull/78
