### ISSUE TITLE
Wie wär's wenn ihr euer sysprog Mal fertig macht ihr snacks

### ISSUE THREAD

**Issue by GuilioHater** [giulionf/realtweetornotbot#76]
**Describe the bug**
unclean code.

**To Reproduce**
1. Go to 'Repo'
2. look at code

**Expected behavior**
you should see unclean code.

**Desktop (please complete the following information):**
 - OS: [WINDOWS-32XX64888]
 - Browser [se one from shower]
 - Version [1]

**Comment by giulionf** [comment]
> **Describe the bug**
> unclean code.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to 'Repo'
> 2. look at code
> 
> **Expected behavior**
> you should see unclean code.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [WINDOWS-32XX64888]
> * Browser [se one from shower]
> * Version [1]

Mudda Hure wer uncleaner Code sagt

**Comment by giulionf** [comment]
F
